// Generated by jextract

package by.mashnyuk.transcriptservice.nativelib.internal;

import by.mashnyuk.transcriptservice.nativelib.WhisperLib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct whisper_timings {
 *     float sample_ms;
 *     float encode_ms;
 *     float decode_ms;
 *     float batchd_ms;
 *     float prompt_ms;
 * }
 * }
 */
public class whisper_timings {

    whisper_timings() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WhisperLib.C_FLOAT.withName("sample_ms"),
        WhisperLib.C_FLOAT.withName("encode_ms"),
        WhisperLib.C_FLOAT.withName("decode_ms"),
        WhisperLib.C_FLOAT.withName("batchd_ms"),
        WhisperLib.C_FLOAT.withName("prompt_ms")
    ).withName("whisper_timings");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfFloat sample_ms$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("sample_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float sample_ms
     * }
     */
    public static final OfFloat sample_ms$layout() {
        return sample_ms$LAYOUT;
    }

    private static final long sample_ms$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float sample_ms
     * }
     */
    public static final long sample_ms$offset() {
        return sample_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float sample_ms
     * }
     */
    public static float sample_ms(MemorySegment struct) {
        return struct.get(sample_ms$LAYOUT, sample_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float sample_ms
     * }
     */
    public static void sample_ms(MemorySegment struct, float fieldValue) {
        struct.set(sample_ms$LAYOUT, sample_ms$OFFSET, fieldValue);
    }

    private static final OfFloat encode_ms$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("encode_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float encode_ms
     * }
     */
    public static final OfFloat encode_ms$layout() {
        return encode_ms$LAYOUT;
    }

    private static final long encode_ms$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float encode_ms
     * }
     */
    public static final long encode_ms$offset() {
        return encode_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float encode_ms
     * }
     */
    public static float encode_ms(MemorySegment struct) {
        return struct.get(encode_ms$LAYOUT, encode_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float encode_ms
     * }
     */
    public static void encode_ms(MemorySegment struct, float fieldValue) {
        struct.set(encode_ms$LAYOUT, encode_ms$OFFSET, fieldValue);
    }

    private static final OfFloat decode_ms$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("decode_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float decode_ms
     * }
     */
    public static final OfFloat decode_ms$layout() {
        return decode_ms$LAYOUT;
    }

    private static final long decode_ms$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float decode_ms
     * }
     */
    public static final long decode_ms$offset() {
        return decode_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float decode_ms
     * }
     */
    public static float decode_ms(MemorySegment struct) {
        return struct.get(decode_ms$LAYOUT, decode_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float decode_ms
     * }
     */
    public static void decode_ms(MemorySegment struct, float fieldValue) {
        struct.set(decode_ms$LAYOUT, decode_ms$OFFSET, fieldValue);
    }

    private static final OfFloat batchd_ms$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("batchd_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float batchd_ms
     * }
     */
    public static final OfFloat batchd_ms$layout() {
        return batchd_ms$LAYOUT;
    }

    private static final long batchd_ms$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float batchd_ms
     * }
     */
    public static final long batchd_ms$offset() {
        return batchd_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float batchd_ms
     * }
     */
    public static float batchd_ms(MemorySegment struct) {
        return struct.get(batchd_ms$LAYOUT, batchd_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float batchd_ms
     * }
     */
    public static void batchd_ms(MemorySegment struct, float fieldValue) {
        struct.set(batchd_ms$LAYOUT, batchd_ms$OFFSET, fieldValue);
    }

    private static final OfFloat prompt_ms$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("prompt_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float prompt_ms
     * }
     */
    public static final OfFloat prompt_ms$layout() {
        return prompt_ms$LAYOUT;
    }

    private static final long prompt_ms$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float prompt_ms
     * }
     */
    public static final long prompt_ms$offset() {
        return prompt_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float prompt_ms
     * }
     */
    public static float prompt_ms(MemorySegment struct) {
        return struct.get(prompt_ms$LAYOUT, prompt_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float prompt_ms
     * }
     */
    public static void prompt_ms(MemorySegment struct, float fieldValue) {
        struct.set(prompt_ms$LAYOUT, prompt_ms$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

