// Generated by jextract

package by.mashnyuk.transcriptservice.nativelib.internal;

import by.mashnyuk.transcriptservice.nativelib.WhisperLib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct whisper_vad_context_params {
 *     int n_threads;
 *     bool use_gpu;
 *     int gpu_device;
 * }
 * }
 */
public class whisper_vad_context_params {

    whisper_vad_context_params() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WhisperLib.C_INT.withName("n_threads"),
        WhisperLib.C_BOOL.withName("use_gpu"),
        MemoryLayout.paddingLayout(3),
        WhisperLib.C_INT.withName("gpu_device")
    ).withName("whisper_vad_context_params");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt n_threads$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_threads"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int n_threads
     * }
     */
    public static final OfInt n_threads$layout() {
        return n_threads$LAYOUT;
    }

    private static final long n_threads$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int n_threads
     * }
     */
    public static final long n_threads$offset() {
        return n_threads$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int n_threads
     * }
     */
    public static int n_threads(MemorySegment struct) {
        return struct.get(n_threads$LAYOUT, n_threads$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int n_threads
     * }
     */
    public static void n_threads(MemorySegment struct, int fieldValue) {
        struct.set(n_threads$LAYOUT, n_threads$OFFSET, fieldValue);
    }

    private static final OfBoolean use_gpu$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("use_gpu"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool use_gpu
     * }
     */
    public static final OfBoolean use_gpu$layout() {
        return use_gpu$LAYOUT;
    }

    private static final long use_gpu$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool use_gpu
     * }
     */
    public static final long use_gpu$offset() {
        return use_gpu$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool use_gpu
     * }
     */
    public static boolean use_gpu(MemorySegment struct) {
        return struct.get(use_gpu$LAYOUT, use_gpu$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool use_gpu
     * }
     */
    public static void use_gpu(MemorySegment struct, boolean fieldValue) {
        struct.set(use_gpu$LAYOUT, use_gpu$OFFSET, fieldValue);
    }

    private static final OfInt gpu_device$LAYOUT = (OfInt)$LAYOUT.select(groupElement("gpu_device"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int gpu_device
     * }
     */
    public static final OfInt gpu_device$layout() {
        return gpu_device$LAYOUT;
    }

    private static final long gpu_device$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int gpu_device
     * }
     */
    public static final long gpu_device$offset() {
        return gpu_device$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int gpu_device
     * }
     */
    public static int gpu_device(MemorySegment struct) {
        return struct.get(gpu_device$LAYOUT, gpu_device$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int gpu_device
     * }
     */
    public static void gpu_device(MemorySegment struct, int fieldValue) {
        struct.set(gpu_device$LAYOUT, gpu_device$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

